### ISSUE TITLE
Error when try to run with Node.js v18 (LTS)

### ISSUE THREAD

**Issue by valdineifer** [ionic-team/photo-gallery-capacitor-react#29]
I got this error right after create the project with `ionic start` and using the template `my-first-app`. I saw that the builder clone this repo, so that's why I created this issue here.

```
valdinei@ideapad:~/dev/ionic-test$ ionic serve
> react-scripts start
[react-scripts] ℹ ｢wds｣: Project is running at http://172.25.17.254/
[react-scripts] ℹ ｢wds｣: webpack output is served from
[react-scripts] ℹ ｢wds｣: Content not from webpack is served from /home/valdinei/dev/ionic-test/public
[react-scripts] ℹ ｢wds｣: 404s will fallback to /
[react-scripts] Starting the development server...
[react-scripts]
[react-scripts] Error: error:0308010C:digital envelope routines::unsupported
[react-scripts]     at new Hash (node:internal/crypto/hash:71:19)
[react-scripts]     at Object.createHash (node:crypto:133:10)
[react-scripts]     at module.exports (/home/valdinei/dev/ionic-test/node_modules/webpack/lib/util/createHash.js:135:53)
[react-scripts]     at NormalModule._initBuildHash (/home/valdinei/dev/ionic-test/node_modules/webpack/lib/NormalModule.js:417:16)
[react-scripts]     at handleParseError (/home/valdinei/dev/ionic-test/node_modules/webpack/lib/NormalModule.js:471:10)
[react-scripts]     at /home/valdinei/dev/ionic-test/node_modules/webpack/lib/NormalModule.js:503:5
[react-scripts]     at /home/valdinei/dev/ionic-test/node_modules/webpack/lib/NormalModule.js:358:12
[react-scripts]     at /home/valdinei/dev/ionic-test/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[react-scripts]     at iterateNormalLoaders (/home/valdinei/dev/ionic-test/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[react-scripts]     at iterateNormalLoaders (/home/valdinei/dev/ionic-test/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[react-scripts] /home/valdinei/dev/ionic-test/node_modules/react-scripts/scripts/start.js:19
[react-scripts]   throw err;
[react-scripts]   ^
[react-scripts] Error: error:0308010C:digital envelope routines::unsupported
[react-scripts]     at new Hash (node:internal/crypto/hash:71:19)
[react-scripts]     at Object.createHash (node:crypto:133:10)
[react-scripts]     at module.exports (/home/valdinei/dev/ionic-test/node_modules/webpack/lib/util/createHash.js:135:53)
[react-scripts]     at NormalModule._initBuildHash (/home/valdinei/dev/ionic-test/node_modules/webpack/lib/NormalModule.js:417:16)
[react-scripts]     at /home/valdinei/dev/ionic-test/node_modules/webpack/lib/NormalModule.js:452:10
[react-scripts]     at /home/valdinei/dev/ionic-test/node_modules/webpack/lib/NormalModule.js:323:13
[react-scripts]     at /home/valdinei/dev/ionic-test/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[react-scripts]     at /home/valdinei/dev/ionic-test/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[react-scripts]     at context.callback (/home/valdinei/dev/ionic-test/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[react-scripts]     at /home/valdinei/dev/ionic-test/node_modules/babel-loader/lib/index.js:59:103 {
[react-scripts]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[react-scripts]   library: 'digital envelope routines',
[react-scripts]   reason: 'unsupported',
[react-scripts]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[react-scripts] }
[react-scripts] Node.js v18.12.1
```

I searched and I saw that's probably the old webpack version, that use the old SSL algorithm, but the new Node versions already use a new algorithm.

**Comment by dotNetkow** [comment]
Thanks for opening the issue! I updated the app to React 18 on main now and a new release.
